### ISSUE TITLE
it seems incompatible with ssl

### ISSUE THREAD

**Issue by JungleWolfz** [nalexandru/api-ms-win-core-path-HACK#10]
i install miniconda Miniconda3-py39_4.12.0-Windows-x86_64.exe on windows7 sp3，and then add  D:\miniconda\Scripts;D:\miniconda;D:\miniconda\Lib\site-packages;D:\miniconda\Library\bin to path.
while  excuting ‘import ssl’，i get error `‘Traceback (most recent call last):
  File "F:\code\stock_walker\test.py", line 3, in <module>
    import ssl
  File "D:\miniconda\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error pro
ImportError: DLL load failed while importing _ssl: 找不到指定的模块。’`

**Comment by nalexandru** [comment]
The problem is not caused by Python or this DLL.
The problem is that it fails to load libssl-1_1-x64.dll from D:\miniconda\Library\bin.

I don't know how to use miniconda, what are the steps to reproduce the error ?
